### Cnoreate a film
@baseUrl = http://localhost:3000
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Nouveau film",
    "duration": 100,
    "budget": 30,
    "link": "https://nouveau.film"
  }

### READ all films
GET {{baseUrl}}/films

### Read all sorted films by duration (ascending)
GET {{baseUrl}}/films/?minimum-duration=1

